include:
  # use template for all stages
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "stages.yml"
  # use template for gitlab pipeline to push main to github
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "publish-to-github.yml"
  # use template for gitlab pipeline to check and build
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "r-check-and-build-packages.yml"

# run check (R CMD check of R package)
r-devtools-check:
  extends:
    - .r-devtools-check

r-pkgdown-build-no-commit:
  extends: ".r-pkgdown-build-no-commit"

# rest of the pipeline: commit and push to github to publish pkgdown site as github pages
# FIXME: Replace with a reference to .publish-main-to-github once the font-free code
# has moved to the main branch.
publish-main-prune-to-github:
  # image specification necessary to have git available
  image: $CI_REGISTRY/docker-hub-proxy/alpine/git:latest
  rules:
    # temporary: we sync the main-prune branch for now, will swap with main once feature parity is established
    - if: $CI_COMMIT_BRANCH == "main-prune"
  extends:
    - .git-setup
  stage: deploy-prod
  script:
    - !reference [.git-setup, script]
    # FIXME: To be removed when moving to main
    - git checkout main-prune
    # This was necessary for the first run:
    # https://cmp-sdlc.stzh.ch/OE-7035/ssz-da/libraries/zueriverse/zueridown/-/jobs/1169750#L46
    # remote: fatal: did not receive expected object 3cfcf5bcf6adbc335521c8f9b793c4aa4f3afe80
    - git fetch --unshallow
    # The code below is the contents of .push-main, can later be changed back to
    #   - !reference [.push-main, script]
    # Expanded here to avoid the semantic conflict with ".push-main" vs. "main-prune".
    - git branch -M main
    - git push -uf github main
