include:
  # use template for gitlab pipeline to check and build
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "r-check-and-build-packages.yml"
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "publish-to-github-components.yml"
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "publish-to-github.yml"

stages:
  - test
  - build
  - deploy-prod
  
# run check (R CMD check of R package)
r-devtools-check:
  extends:
    - .r-devtools-check
    
r-pkgdown-build-no-commit:
  extends: ".r-pkgdown-build-no-commit"

# rest of the pipeline: build pkgdown site, remove almost everything except dummy readme and pkgdown site
# then commit and push to github to publish pkgdown site as github pages
build-remove-orphan-push:
  image: $CI_REGISTRY/docker-hub-proxy/rocker/tidyverse:4.3.2
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  extends:
    - .common-settings-publish-to-github
    - .common-settings-check-and-build
    - .git-setup
    - .orphan-commit-push
  stage: deploy-prod
  script:
    - !reference [.git-setup, script]
    - Rscript -e "renv::status()"
    - mkdir pkgdown
    # use normal readme for pkgdown home site
    - cp README.md pkgdown/index.md
    # create dummy readme to be shown in github as readme
    - cp dev/dummy_README.md README.md
    # remove stuff that is not needed
    - rm  .gitlab-ci.yml .Rbuildignore .Rprofile
    - rm -r -f -v dev inst R 
    - ls -R
    - git add .
    - git commit -m "remove fonts etc., swap readmes"
    - !reference [.orphan-commit-push, script]
    