#' A wraper to indiedown::pdf_document_with_asset() that will be auto generated by a helper function in indiedown
#'
#' @export
zueridown <- function(...) {
  indiedown_pdf_document_with_asset(
    highlight = "pygments",
    latex_engine = "xelatex",
    ...
  )
}
